# A dictionary mapping font family names to their variable font files.
# The 'url' now directly points to the correct font file for that style.
VARIABLE_FONTS = {
    "aileron-thin": {
        "format": "woff2",
        "weight_range": "100",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-Thin.woff2",
    },
    "aileron-thin-italic": {
        "format": "woff2",
        "weight_range": "100",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-ThinItalic.woff2",
    },
    "aileron-ultra-light": {
        "format": "woff2",
        "weight_range": "200",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-UltraLight.woff2",
    },
    "aileron-ultra-light-italic": {
        "format": "woff2",
        "weight_range": "200",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-UltraLightItalic.woff2",
    },
    "aileron-light": {
        "format": "woff2",
        "weight_range": "300",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-Light.woff2",
    },
    "aileron-light-italic": {
        "format": "woff2",
        "weight_range": "300",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-LightItalic.woff2",
    },
    "aileron": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-Regular.woff2",
    },
    "aileron-italic": {
        "format": "woff2",
        "weight_range": "400",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-Italic.woff2",
    },
    "aileron-semi-bold": {
        "format": "woff2",
        "weight_range": "600",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-SemiBold.woff2",
    },
    "aileron-semi-bold-italic": {
        "format": "woff2",
        "weight_range": "600",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-SemiBoldItalic.woff2",
    },
    "aileron-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-Bold.woff2",
    },
    "aileron-bold-italic": {
        "format": "woff2",
        "weight_range": "700",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-BoldItalic.woff2",
    },
    "aileron-heavy": {
        "format": "woff2",
        "weight_range": "800",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-Heavy.woff2",
    },
    "aileron-heavy-italic": {
        "format": "woff2",
        "weight_range": "800",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-HeavyItalic.woff2",
    },
    "aileron-black": {
        "format": "woff2",
        "weight_range": "900",
        "style": "normal",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-Black.woff2",
    },
    "aileron-black-italic": {
        "format": "woff2",
        "weight_range": "900",
        "style": "italic",
        "font_family_name": "Aileron",
        "folder_name": "Aileron",
        "file_name": "Aileron-BlackItalic.woff2",
    },
    "arapey": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Arapey",
        "folder_name": "Arapey",
        "file_name": "Arapey-Regular.woff2",
    },
    "arapey-italic": {
        "format": "woff2",
        "weight_range": "400",
        "style": "italic",
        "font_family_name": "Arapey",
        "folder_name": "Arapey",
        "file_name": "Arapey-Italic.woff2",
    },
    "bebas-neue": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Bebas Neue",
        "folder_name": "Bebas_Neue",
        "file_name": "BebasNeue-Regular.woff2",
    },
    "comic-relief": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Comic Relief",
        "folder_name": "Comic_Relief",
        "file_name": "ComicRelief-Regular.woff2",
    },
    "comic-relief-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Comic Relief",
        "folder_name": "Comic_Relief",
        "file_name": "ComicRelief-Bold.woff2",
    },
    "dm-serif-display": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "DM Serif Display",
        "folder_name": "DM_Serif_Display",
        "file_name": "DMSerifDisplay-Regular.woff2",
    },
    "dm-serif-display-italic": {
        "format": "woff2",
        "weight_range": "400",
        "style": "italic",
        "font_family_name": "DM Serif Display",
        "folder_name": "DM_Serif_Display",
        "file_name": "DMSerifDisplay-Italic.woff2",
    },
    "futura": {
        "format": "woff2",
        "weight_range": "300",
        "style": "normal",
        "font_family_name": "Futura",
        "folder_name": "Futura",
        "file_name": "FuturaStd-Light.woff2",
    },
    "futura-italic": {
        "format": "woff2",
        "weight_range": "300",
        "style": "italic",
        "font_family_name": "Futura",
        "folder_name": "Futura",
        "file_name": "FuturaStd-LightOblique.woff2",
    },
    "konya": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Konya",
        "folder_name": "Konya",
        "file_name": "Konya.woff2",
    },
    "lato": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "Lato-Regular-latin.woff2",
    },
    "lato-italic": {
        "format": "woff2",
        "weight_range": "400",
        "style": "italic",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-Italic.woff2",
    },
    "lato-black": {
        "format": "woff2",
        "weight_range": "900",
        "style": "normal",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-Black.woff2",
    },
    "lato-black-italic": {
        "format": "woff2",
        "weight_range": "900",
        "style": "italic",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-BlackItalic.woff2",
    },
    "lato-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "Lato-Bold-latin.woff2",
    },
    "lato-bold-italic": {
        "format": "woff2",
        "weight_range": "700",
        "style": "italic",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-BoldItalic.woff2",
    },
    "lato-thin": {
        "format": "woff2",
        "weight_range": "100",
        "style": "normal",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-Hairline.woff2",
    },
    "lato-thin-italic": {
        "format": "woff2",
        "weight_range": "100",
        "style": "italic",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-HairlineItalic.woff2",
    },
    "lato-light": {
        "format": "woff2",
        "weight_range": "300",
        "style": "normal",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-Light.woff2",
    },
     "lato-light-italic": {
        "format": "woff2",
        "weight_range": "300",
        "style": "italic",
        "font_family_name": "Lato",
        "folder_name": "Lato",
        "file_name": "Lato-LightItalic.woff2",
    },
    "poppins-thin": {
        "format": "woff2",
        "weight_range": "100",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-Thin.woff2",
    },
    "poppins-thin-italic": {
        "format": "woff2",
        "weight_range": "100",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-ThinItalic.woff2",
    },
    "poppins-extra-light": {
        "format": "woff2",
        "weight_range": "200",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-ExtraLight.woff2",
    },
    "poppins-extra-light-italic": {
        "format": "woff2",
        "weight_range": "200",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-ExtraLightItalic.woff2",
    },
    "poppins-light": {
        "format": "woff2",
        "weight_range": "300",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-Light.woff2",
    },
    "poppins-light-italic": {
        "format": "woff2",
        "weight_range": "300",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-LightItalic.woff2",
    },
    "poppins": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "Poppins-Regular-latin.woff2",
    },
    "poppins-italic": {
        "format": "woff2",
        "weight_range": "400",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-Italic.woff2",
    },
    "poppins-medium": {
        "format": "woff2",
        "weight_range": "500",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-Medium.woff2",
    },
    "poppins-medium-italic": {
        "format": "woff2",
        "weight_range": "500",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-MediumItalic.woff2",
    },
    "poppins-semi-bold": {
        "format": "woff2",
        "weight_range": "600",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-SemiBold.woff2",
    },
    "poppins-semi-bold-italic": {
        "format": "woff2",
        "weight_range": "600",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-SemiBoldItalic.woff2",
    },
    "poppins-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "Poppins-Bold-latin.woff2",
    },
    "poppins-bold-italic": {
        "format": "woff2",
        "weight_range": "700",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-BoldItalic.woff2",
    },
    "poppins-extra-bold": {
        "format": "woff2",
        "weight_range": "800",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-ExtraBold.woff2",
    },
    "poppins-extra-bold-italic": {
        "format": "woff2",
        "weight_range": "800",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-ExtraBoldItalic.woff2",
    },
    "poppins-black": {
        "format": "woff2",
        "weight_range": "900",
        "style": "normal",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-Black.woff2",
    },
    "poppins-black-italic": {
        "format": "woff2",
        "weight_range": "900",
        "style": "italic",
        "font_family_name": "Poppins",
        "folder_name": "Poppins",
        "file_name": "Poppins-BlackItalic.woff2",
    },
    "pt-sans-caption": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "PT Sans Caption",
        "folder_name": "PT_Sans_Caption",
        "file_name": "PTSans-Caption.woff2",
    },
    "pt-sans-caption-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "PT Sans Caption",
        "folder_name": "PT_Sans_Caption",
        "file_name": "PTSans-CaptionBold.woff2",
    },
    "quantico": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Quantico",
        "folder_name": "Quantico",
        "file_name": "Quantico-Regular.woff2",
    },
    "quantico-italic": {
        "format": "woff2",
        "weight_range": "400",
        "style": "italic",
        "font_family_name": "Quantico",
        "folder_name": "Quantico",
        "file_name": "Quantico-Italic.woff2",
    },
    "quantico-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Quantico",
        "folder_name": "Quantico",
        "file_name": "Quantico-Bold.woff2",
    },
    "quantico-bold-italic": {
        "format": "woff2",
        "weight_range": "700",
        "style": "italic",
        "font_family_name": "Quantico",
        "folder_name": "Quantico",
        "file_name": "Quantico-BoldItalic.woff2",
    },
    "slabo": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Slabo",
        "folder_name": "Slabo_27px",
        "file_name": "Slabo27px-Regular.woff2",
    },
    "themify": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Themify",
        "folder_name": "Themify",
        "file_name": "themify.woff2",
    },
    "ubuntu-titling": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Ubuntu Titling",
        "folder_name": "Ubuntu",
        "file_name": "UbuntuTitling-Bold.woff2",
    },
    "pt-serif": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "PT Serif",
        "folder_name": "PT_Serif",
        "file_name": "PTSerif-Regular.woff2",
    },
    "pt-serif-italic": {
        "format": "woff2",
        "weight_range": "400",
        "style": "italic",
        "font_family_name": "PT Serif",
        "folder_name": "PT_Serif",
        "file_name": "PTSerif-Italic.woff2",
    },
    "pt-serif-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "PT Serif",
        "folder_name": "PT_Serif",
        "file_name": "PTSerif-Bold.woff2",
    },
    "pt-serif-bold-italic": {
        "format": "woff2",
        "weight_range": "700",
        "style": "italic",
        "font_family_name": "PT Serif",
        "folder_name": "PT_Serif",
        "file_name": "PTSerif-BoldItalic.woff2",
    },
    "heebo": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "normal",
        "font_family_name": "Heebo",
        "folder_name": "Heebo",
        "file_name": "Heebo-Variable.woff2",
    },
    "karla": {
        "format": "woff2",
        "weight_range": "200 800",
        "style": "normal",
        "font_family_name": "Karla",
        "folder_name": "Karla",
        "file_name": "Karla-Variable.woff2",
    },
    "karla-italic": {
        "format": "woff2",
        "weight_range": "200 800",
        "style": "italic",
        "font_family_name": "Karla",
        "folder_name": "Karla",
        "file_name": "Karla-VariableItalic.woff2",
    },
    "lora": {
        "format": "woff2",
        "weight_range": "400 700",
        "style": "normal",
        "font_family_name": "Lora",
        "folder_name": "Lora",
        "file_name": "Lora-Variable.woff2",
    },
    "lora-italic": {
        "format": "woff2",
        "weight_range": "400 700",
        "style": "italic",
        "font_family_name": "Lora",
        "folder_name": "Lora",
        "file_name": "Lora-VariableItalic.woff2",
    },
    "merriweather": {
        "format": "woff2",
        "weight_range": "300 900",
        "style": "normal",
        "font_family_name": "Merriweather",
        "folder_name": "Merriweather",
        # LATIN SUBSET. Same family, same weight axes, same appearance -- 286 glyphs instead of 1508,
        # with Cyrillic/Greek/Vietnamese/Latin-Extended dropped and OpenType features pruned to the ones
        # our CSS actually invokes (kern/liga/calt/mark). 433 KB -> 93 KB.
        #
        # A NEW filename on purpose: these files are served `immutable` for a year, so replacing one in
        # place would keep serving the old bytes from every warm CloudFront edge. The full-charset file
        # is still in the bucket, so reverting is this one line.
        "file_name": "Merriweather-Variable-latin.woff2",
    },
    "merriweather-italic": {
        "format": "woff2",
        "weight_range": "300 900",
        "style": "italic",
        "font_family_name": "Merriweather",
        "folder_name": "Merriweather",
        "file_name": "Merriweather-VariableItalic.woff2",
    },
    "merriweather-sans": {
        "format": "woff2",
        "weight_range": "300 800",
        "style": "normal",
        "font_family_name": "Merriweather Sans",
        "folder_name": "Merriweather_Sans",
        "file_name": "MerriweatherSans-Variable.woff2",
    },
    "merriweather-sans-italic": {
        "format": "woff2",
        "weight_range": "300 800",
        "style": "italic",
        "font_family_name": "Merriweather Sans",
        "folder_name": "Merriweather_Sans",
        "file_name": "MerriweatherSans-VariableItalic.woff2",
    },
    "montserrat": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "normal",
        "font_family_name": "Montserrat",
        "folder_name": "Montserrat",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "Montserrat-Variable-latin.woff2",
    },
    "montserrat-italic": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "italic",
        "font_family_name": "Montserrat",
        "folder_name": "Montserrat",
        "file_name": "Montserrat-VariableItalic.woff2",
    },
    "nunito": {
        "format": "woff2",
        "weight_range": "200 1000",
        "style": "normal",
        "font_family_name": "Nunito",
        "folder_name": "Nunito",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "Nunito-Variable-latin.woff2",
    },
    "nunito-italic": {
        "format": "woff2",
        "weight_range": "200 1000",
        "style": "italic",
        "font_family_name": "Nunito",
        "folder_name": "Nunito",
        "file_name": "Nunito-VariableItalic.woff2",
    },
    "open-sans": {
        "format": "woff2",
        "weight_range": "300 800",
        "style": "normal",
        "font_family_name": "Open Sans",
        "folder_name": "Open_Sans",
        "file_name": "OpenSans-Variable.woff2",
    },
    "open-sans-italic": {
        "format": "woff2",
        "weight_range": "300 800",
        "style": "italic",
        "font_family_name": "Open Sans",
        "folder_name": "Open_Sans",
        "file_name": "OpenSans-VariableItalic.woff2",
    },
    "oswald": {
        "format": "woff2",
        "weight_range": "200 700",
        "style": "normal",
        "font_family_name": "Oswald",
        "folder_name": "Oswald",
        "file_name": "Oswald-Variable.woff2",
    },
    "overpass": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "normal",
        "font_family_name": "Overpass",
        "folder_name": "Overpass",
        "file_name": "Overpass-Variable.woff2",
    },
    "overpass-italic": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "italic",
        "font_family_name": "Overpass",
        "folder_name": "Overpass",
        "file_name": "Overpass-VariableItalic.woff2",
    },
    "overpass-mono": {
        "format": "woff2",
        "weight_range": "300 700",
        "style": "normal",
        "font_family_name": "Overpass Mono",
        "folder_name": "Overpass_Mono",
        "file_name": "OverpassMono-Variable.woff2",
    },
    "playfair": {
        "format": "woff2",
        "weight_range": "300 900",
        "style": "normal",
        "font_family_name": "Playfair",
        "folder_name": "Playfair",
        "file_name": "Playfair-Variable.woff2",
    },
    "playfair-italic": {
        "format": "woff2",
        "weight_range": "300 900",
        "style": "italic",
        "font_family_name": "Playfair",
        "folder_name": "Playfair",
        "file_name": "Playfair-VariableItalic.woff2",
    },
    "quicksand": {
        "format": "woff2",
        "weight_range": "300 700",
        "style": "normal",
        "font_family_name": "Quicksand",
        "folder_name": "Quicksand",
        "file_name": "Quicksand-Variable.woff2",
    },
    "raleway": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "normal",
        "font_family_name": "Raleway",
        "folder_name": "Raleway",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "Raleway-Variable-latin.woff2",
    },
    "raleway-italic": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "italic",
        "font_family_name": "Raleway",
        "folder_name": "Raleway",
        "file_name": "Raleway-VariableItalic.woff2",
    },
    "roboto": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "normal",
        "font_family_name": "Roboto",
        "folder_name": "Roboto",
        "file_name": "Roboto-Variable.woff2",
    },
    "roboto-italic": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "italic",
        "font_family_name": "Roboto",
        "folder_name": "Roboto",
        "file_name": "Roboto-VariableItalic.woff2",
    },
    "rubik": {
        "format": "woff2",
        "weight_range": "300 900",
        "style": "normal",
        "font_family_name": "Rubik",
        "folder_name": "Rubik",
        "file_name": "Rubik-Variable.woff2",
    },
    "rubik-italic": {
        "format": "woff2",
        "weight_range": "300 900",
        "style": "italic",
        "font_family_name": "Rubik",
        "folder_name": "Rubik",
        "file_name": "Rubik-VariableItalic.woff2",
    },
    "inter": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "normal",
        "font_family_name": "Inter",
        "folder_name": "Inter",
        # LATIN SUBSET. Same family, same weight axes, same appearance -- 385 glyphs instead of 1742,
        # with Cyrillic/Greek/Vietnamese/Latin-Extended dropped and OpenType features pruned to the ones
        # our CSS actually invokes (kern/liga/calt/mark). 203 KB -> 63 KB.
        #
        # A NEW filename on purpose: these files are served `immutable` for a year, so replacing one in
        # place would keep serving the old bytes from every warm CloudFront edge. The full-charset file
        # is still in the bucket, so reverting is this one line.
        "file_name": "Inter-Variable-latin.woff2",
    },
    "inter-italic": {
        "format": "woff2",
        "weight_range": "100 900",
        "style": "italic",
        "font_family_name": "Inter",
        "folder_name": "Inter",
        "file_name": "Inter-VariableItalic.woff2",
    },
    # Add more variable fonts here as needed
    # The variable cut, same family name as the statics below -- a drop-in, no page migration. It wins for
    # any weight in 200-900 because find_best_weight_match returns a variable range immediately; the static
    # faces stay registered deliberately, as the fallback for a weight OUTSIDE that range.
    "source-code-pro-variable": {
        "format": "woff2",
        "weight_range": "200 900",
        "style": "normal",
        "font_family_name": "Source Code Pro",
        "folder_name": "Source_Code_Pro",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "SourceCodePro-Variable-latin.woff2",
    },
    "source-code-pro-regular": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Source Code Pro",
        "folder_name": "Source_Code_Pro",
        "file_name": "SourceCodePro-Regular.woff2",
    },
    "source-code-pro-semibold": {
        "format": "woff2",
        "weight_range": "600",
        "style": "normal",
        "font_family_name": "Source Code Pro",
        "folder_name": "Source_Code_Pro",
        "file_name": "SourceCodePro-SemiBold.woff2",
    },
    "source-code-pro-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Source Code Pro",
        "folder_name": "Source_Code_Pro",
        "file_name": "SourceCodePro-Bold.woff2",
    },
    # Source Sans 3 is the upstream SUCCESSOR to Source Sans Pro, which Adobe retired. It is a genuine
    # variable font (wght 200-900) in ONE file, so every heading weight renders a real face instead of a
    # browser-faked bold. Source Sans Pro stays catalogued: pages already store that family name, and
    # dropping it would re-typeset them without asking.
    "source-sans-3-variable": {
        "format": "woff2",
        "weight_range": "200 900",
        "style": "normal",
        "font_family_name": "Source Sans 3",
        "folder_name": "Source_Sans_3",
        # Latin subset -- see the Merriweather entry above for why these carry a new filename rather
        # than replacing the original in place.
        "file_name": "SourceSans3-Variable-latin.woff2",
    },
    "source-sans-pro-regular": {
        "format": "woff2",
        "weight_range": "400",
        "style": "normal",
        "font_family_name": "Source Sans Pro",
        "folder_name": "Source_Sans_Pro",
        "file_name": "SourceSansPro-Regular.woff2",
    },
    "source-sans-pro-semibold": {
        "format": "woff2",
        "weight_range": "600",
        "style": "normal",
        "font_family_name": "Source Sans Pro",
        "folder_name": "Source_Sans_Pro",
        "file_name": "SourceSansPro-SemiBold.woff2",
    },
    "source-sans-pro-bold": {
        "format": "woff2",
        "weight_range": "700",
        "style": "normal",
        "font_family_name": "Source Sans Pro",
        "folder_name": "Source_Sans_Pro",
        "file_name": "SourceSansPro-Bold.woff2",
    },
}